sudo: required
language: c

matrix:
  include:
    - os: linux
      dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc python3-pip valgrind

install:
  - export PATH="`pwd`/build:${PATH}"
  - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build
  - pip3 install meson

script:
  - meson builddir
  - ninja -C builddir
  - mesontest -C builddir --print-errorlogs
  - mesontest -C builddir --print-errorlogs --num-processes 1 --wrapper "valgrind --leak-check=full --malloc-fill=1 --free-fill=1"
