site_name: b6b
repo_url: https://github.com/dimkr/b6b
pages:
- Overview:
    - Introduction: introduction.md
    - Use Cases: use_cases.md
- Tutorial: tutorial.md
- Standard Library: stdlib.md
- I/O:
    - Streams: streams.md
    - Event Loops: evloop.md
    - File System: fs.md
- Bindings: bindings.md
- License: license.md
