.TH b6b 1
.SH NAME
.B b6b
\- b6b script interpreter
.SH SYNOPSIS
.B b6b
[\fIoption\fR]... [\fIscript\fR] [\fIarg\fR]...
.SH DESCRIPTION
Runs \fIscript\fR or an interactive scripting shell.
.SH OPTIONS
.TP
.B -c
Run \fIscript\fR instead of running statements in the file at \fIscript\fR.
.TP
.B -e
Propagate errors caught by \fBtry\fR blocks.
.TP
.B -u
Disable buffering of input and output through standard input pipes.
.TP
.B -x
Write each statement before it is executed.
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
